name: Python package

on:
  push:
    branches:
      - main  # Change this to the branch you're working with (if not 'main')
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Use the Python version you're working with

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a requirements.txt

    - name: Run tests with pytest
      run: |
        pip install pytest coverage
        coverage run -m pytest  # Run tests with coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml  # Upload the coverage report
        token: ${{ secrets.CODECOV_TOKEN }}  # Use the Codecov token (see below)
